"""account_confirm

Revision ID: 981c59540c07
Revises: edb5e300f5f8
Create Date: 2017-05-27 21:48:53.991000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '981c59540c07'
down_revision = 'edb5e300f5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_column('email')
        batch_op.drop_column('confirmed')
    # ### end Alembic commands ###
